#!/bin/sh

. /lib/functions.sh

board=$(board_name)

case "$board" in
devolo,dlan-hotspot)
	echo 0 > /sys/class/gpio/gpio20/value
	sleep 1
	echo 1 > /sys/class/gpio/gpio20/value
	;;

devolo,dlan-pro-500-wp)
	echo 0 > /sys/class/gpio/gpio13/value
	sleep 1
	echo 1 > /sys/class/gpio/gpio13/value
	;;

devolo,dlan-pro-1200-ac|\
devolo,dlan-pro-1200-n)
	echo 0 > /sys/class/gpio/gpio13/value
	sleep 1
	echo 1 > /sys/class/gpio/gpio13/value
	;;

*)
	echo "$0: unknown board $board" >&2
	exit 1;
	;;
esac
